spring.application.name=SeatReservationEngine

spring.datasource.url = jdbc:mysql://localhost:3306/concert_booking

spring.datasource.username = root

spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto = update